const lotTypes = [
  null,
  "Group Lot",
  "Lake Lot",
  "Outer Two Mile",
  "Park Lot",
  "River Lot",
  "Settlement Lot",
  "Wood Lot",
  "Indian Reserve"
];

const parishes = [
  null,
  "Baie Saint Paul",
  "Big Eddy",
  "Brokenhead",
  "Cross Lake",
  "Duck Bay North",
  "Duck Bay South",
  "Fairford",
  "Fairford Mission",
  "Fisher Bay",
  "Fort Alexander",
  "Grand Rapids",
  "Grande Pointe",
  "Headingley",
  "High Bluff",
  "Kildonan",
  "Lorette",
  "Manigotagan River",
  "Manitoba House",
  "Norway House",
  "Oak Island",
  "Oak Point",
  "Pasquia",
  "Pine Creek",
  "Poplar Point",
  "Portage La Prairie",
  "Rat River",
  "Riding Mountain National Park",
  "Roman Catholic Mission Property",
  "Saint Andrews",
  "Saint Boniface",
  "Saint Charles",
  "Saint Clements",
  "Saint Francois Xavier",
  "Saint James",
  "Saint John",
  "Saint Laurent",
  "Saint Malo",
  "Saint Norbert",
  "Saint Paul",
  "Saint Peter",
  "Saint Vital",
  "Sainte Agathe",
  "Sainte Anne",
  "The Pas",
  "Umfreville",
  "Westbourne"
];

module.exports = { lotTypes, parishes };
